export const NICHOS = [
  "Academias e Estúdios",
  "Administradoras",
  "Advocacia",
  "Agências de Marketing",
  "Agronegócio",
  "Alimentação / Restaurantes",
  "Arquitetura e Design",
  "Automotivo",
  "Clínicas de Estética",
  "Clínicas Médicas",
  "Clínicas Odontológicas",
  "Comércio Atacadista",
  "Comércio Varejista",
  "Comunicação e Mídia",
  "Construção Civil",
  "Construtoras",
  "Consultorias",
  "Contabilidades",
  "Corretoras de Seguros",
  "Cursos Profissionalizantes",
  "D2C",
  "Distribuidores",
  "Educação / Cursos",
  "E-commerce",
  "Empresas de Serviços B2B",
  "Energia Solar",
  "Engenharia",
  "Entretenimento e Cultura",
  "Escolas",
  "Escritórios de Advocacia",
  "Esportes e Fitness",
  "Estética",
  "Estética Automotiva",
  "Farmacêutica",
  "Financeiro",
  "Fintechs",
  "Imobiliárias",
  "Indústrias",
  "Infoprodutores",
  "Logística e Transporte",
  "Lojas Virtuais",
  "Marketing e Publicidade",
  "Marketing Digital",
  "Outros",
  "Prestadores de Serviço",
  "Representações Comerciais",
  "SaaS",
  "Segurança Patrimonial",
  "Seguros",
  "Startups",
  "Tecnologia da Informação",
  "Transportes",
  "Turismo e Hospitalidade",
].sort();