// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://dmbdzcqafnmmilxvlttp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRtYmR6Y3FhZm5tbWlseHZsdHRwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njc4ODA2NDEsImV4cCI6MjA4MzQ1NjY0MX0.sJm0w-ZpdgGjp-wcefjrQgA2bRG65F49XaHUSYFwrWg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);